In [22]:
import numpy as np

In [23]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([[-10, 0, 17],
             [5, 3, 9],
        [-6, 2, -2]], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[[-10.   0.  17.]
 [  5.   3.   9.]
 [ -6.   2.  -2.]]


In [24]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3, 3)


In [25]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [[-1.75        0.98333333  4.73333333]
 [ 1.75        1.28333333  0.53333333]
 [ 2.25       -0.08333333 -0.33333333]]


In [26]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -60.00


In [27]:
A_system = np.hstack((A, b.reshape((3, 3))))

print(A_system)

[[  4.  -3.   1. -10.   0.  17.]
 [  2.   1.   3.   5.   3.   9.]
 [ -1.   2.  -5.  -6.   2.  -2.]]


In [28]:
# exchange row_num of the matrix M with its multiple by row_num_multiple
# Note: for simplicity, you can drop check if  row_num_multiple has non-zero value, which makes the operation valid
def MultiplyRow(M, row_num, row_num_multiple):
    # .copy() function is required here to keep the original matrix without any changes
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new

print("Original matrix:")
print(A_system)
print("\nMatrix after its third row is multiplied by 2:")
# remember that indexing in Python starts from 0, thus index 2 will correspond to the third row
print(MultiplyRow(A_system,2,2))

Original matrix:
[[  4.  -3.   1. -10.   0.  17.]
 [  2.   1.   3.   5.   3.   9.]
 [ -1.   2.  -5.  -6.   2.  -2.]]

Matrix after its third row is multiplied by 2:
[[  4.  -3.   1. -10.   0.  17.]
 [  2.   1.   3.   5.   3.   9.]
 [ -2.   4. -10. -12.   4.  -4.]]


In [29]:
def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new

print("Original matrix:")
print(A_system)
print("\nMatrix after exchange its first and third rows:")
print(SwapRows(A_system,0,2))

Original matrix:
[[  4.  -3.   1. -10.   0.  17.]
 [  2.   1.   3.   5.   3.   9.]
 [ -1.   2.  -5.  -6.   2.  -2.]]

Matrix after exchange its first and third rows:
[[ -1.   2.  -5.  -6.   2.  -2.]
 [  2.   1.   3.   5.   3.   9.]
 [  4.  -3.   1. -10.   0.  17.]]


In [30]:
A_ref = SwapRows(A_system,0,2)
# Note: ref is an abbreviation of the row echelon form (row reduced form)
print(A_ref)

[[ -1.   2.  -5.  -6.   2.  -2.]
 [  2.   1.   3.   5.   3.   9.]
 [  4.  -3.   1. -10.   0.  17.]]


In [31]:
A_2 = np.array([
        [1, 1, 1],
        [0, 1, -3],
        [2, 1, 5]
    ], dtype=np.dtype(float))

b_2 = np.array([2, 1, 0], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00
