In [3]:
import numpy as np



In [4]:

import w2_unittest

In [5]:
A = np.array([     
        [2,-1,1,1],
        [1,2,-1,-1],
        [-1,2,2,2],
        [1,-1,2,1]    
    ], dtype=np.dtype(float)) 
b = np.array([6,3,14,8], dtype=np.dtype(float))
print(A)
print(b)

[[ 2. -1.  1.  1.]
 [ 1.  2. -1. -1.]
 [-1.  2.  2.  2.]
 [ 1. -1.  2.  1.]]
[ 6.  3. 14.  8.]


In [6]:

w2_unittest.test_matrix(A, b)

 All tests passed
